name: 生成JKS证书（文件名为release）

on:
  workflow_dispatch:

jobs:
  generate-jks:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: 生成JKS证书（文件名为release）
        run: |
          keytool -genkeypair \
            -alias androidcert \
            -keyalg RSA \
            -keysize 2048 \
            -validity 3650 \
            -keystore release.jks \
            -storepass dfsstoremidea \
            -keypass dfsmidea \
            -dname "CN=TestApp, OU=Android, O=TestOrg, L=Beijing, ST=Beijing, C=CN"

      - name: 提交证书到代码库
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add release.jks  # 添加名为release.jks的证书
          git commit -m "Auto-generate JKS certificate (filename: release.jks)"
          git push
